spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/xnote?rewriteBatchedStatements=true
    username: root
    password: 123456
  redis:
    host: localhost
    port: 6379
    password: 123456
  mail:
    host: smtp.qq.com
    port: 587
    username: ${EMAIL_ADDRESS}
    password: ${EMAIL_PASSWORD}
  elasticsearch:
    uris: http://localhost:9200
    username: xclhove
    password: 123456

minio:
  endpoint: http://localhost:9101
  remoteEndpoint: http://localhost:9101
  bucketName: xnote
  accessKey: admin
  secretKey: 12345678

xnote:
  debug:
    enable-mock-send-verification-code: true
    enable-verify-verification-code: true
  runner:
    enable-check-redis-status: true
    enable-check-minio-status: true
    send-startup-email: true
    import-data-from-database-to-elastic-search: false
    update-image-size: false
    create-default-note-type-for-user-of-none-type: false
    replace-image-url-in-note: false
  interceptor:
    ip:
      disable: true
      max-frequency-per-minute: 120
    device:
      disable: true
      max-frequency-per-minute: 120
  image:
    allow-size-of-byte: 10485760
  search:
    height-light-content-max-length: 400