#配置选择 dev:开发环境 | test:测试环境 | pro:生产环境
spring.profiles.active: dev
#spring banner
spring.main.banner-mode: off
#mybatis-plus banner
mybatis-plus.global-config.banner: off
#数据库id自增
mybatis-plus.global-config.db-config.id-type: auto
#数据库驱动名
spring.datasource.driver-class-name: com.mysql.cj.jdbc.Driver
#服务名称
spring.application.name: xnote
# 日志配置
logging:
  file:
    # 日志文件名格式
    name: ${user.home}/logs/${spring.application.name}/${spring.application.name}.log
  pattern:
    # 日志记录格式[时间戳] [日志级别] [类名.方法名] [消息文本]
    #file: xfile-%d{yyyy-MM-dd HH:mm:ss.SSS} %p %C.%M %m %n
    file: xfile-%d{yyyy-MM-dd HH:mm:ss} %p %C.%M %m %n
  logback:
    rollingpolicy:
      # 根据文件大小归档，超过10MB自动归档，次日启动服务时也会自动归档
      file-name-pattern: ${user.home}/logs/${spring.application.name}/${spring.application.name}.%d{yyyy-MM-dd}.%i.gz
      # 最大日志文件大小(默认为10MB)
      max-file-size: 1MB
      # 要保留的日志备份的总大小(默认为0B)
      total-size-cap: 1GB
      # 保存存档日志文件的最大天数(默认为7天)
      max-history: 30
#flyway
spring.flyway:
  enabled: true
  # flyway 的 clean 命令会删除指定 schema 下的所有 table, 生产务必禁掉。
  clean-disabled: true
#swagger
spring.mvc.pathmatch.matching-strategy: ant_path_matcher
#MybatisEnumTypeHandler
mybatis-plus.configuration.default-enum-type-handler: com.baomidou.mybatisplus.core.handlers.MybatisEnumTypeHandler
spring.thymeleaf.check-template-location: false
#为null时不返回属性
spring.jackson.default-property-inclusion: NON_EMPTY

xnote:
  ip:
   max-frequency-per-minute: 120 #单个ip每分钟最大请求次数
  image:
    allow-type: ^image/(png|jpg|jpeg|svg|ico|gif|bmp)+$ #允许上传的图片类型
    allow-size: 10485760 #10MB
  page-request:
    max-page-size: 100 #分页请求每页最大数量
  runner:
    enable-keywords-convert-runner: false
    enable-minio-status-check-runner: true
    enable-redis-status-check-runner: true
    enable-image-url-replace-runner: false
  debug:
    enable: true
---
#应用服务WEB访问端口
server.port: 8080

spring:
  config:
    activate:
      on-profile: dev
  #数据库配置
  datasource:
    #MysqlUrl格式: jdbc:mysql://IP:Port/DataBaseName?parameter=value
    url: jdbc:mysql://localhost:3306/xnote?rewriteBatchedStatements=true
    #数据库用户名
    username: root
    #数据库密码
    password: 123456
  redis:
    host: localhost
    port: 6379
    password: 123456
    database: 0
  mail:
    host: smtp.qq.com
    port: 587
    username: 2959169303@qq.com
    password: 123456

#mybatis-plus 控制台打印完整带参数SQL语句
mybatis-plus.configuration.log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
logging:
  level:
    root: info

#minio
minio:
  endpoint: http://localhost:9090 #Minio服务所在地址
  bucketName: xnote #存储桶名称
  accessKey: admin #访问的key
  secretKey: 12345678 #访问的秘钥